name: luckeverydaybot
description: A simple telegram bot for placing casino like bets.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  cron: ^0.6.1
  intl: ^0.20.2
  supabase: ^2.6.3
  televerse: ^2.4.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
